### ISSUE TITLE
Can't Combine Candlestick and Line charts in Blazor-ApexCharts

### ISSUE THREAD

**Issue by ShrewdMensch** [apexcharts/Blazor-ApexCharts#68]
Hello,
I was trying to combine Candlestick and Line charts, but I got an error:

**System.AggregateException: One or more errors occurred. (Chart Type Candlestick connot be mixed)
 ---> System.Exception: Chart Type Candlestick connot be mixed
   at ApexCharts.ApexChart`1.GetMixedChartType(ChartType chartType)
   at ApexCharts.ApexChart`1.SetSeries()
   at ApexCharts.ApexChart`1.PrepareChart()
   at ApexCharts.ApexChart`1.RenderChartAsync()
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---**

**And the combo is possible with pure Apex.js**

**_Is there a way I make such combo with Blazor_ApexCharts or it is not currently supported?_**

Thank you.

**Comment by joadan** [comment]
Hello,

Looks like I'm to restrictive when checking what can be mixed.
I'll look into it.

**Comment by ShrewdMensch** [comment]
> Hello,
> 
> Looks like I'm to restrictive when checking what can be mixed. I'll look into it.

Alright Joadan.
I will be expecting your prompt feedback.

Regards.

**Comment by joadan** [comment]
Check sample https://apexcharts.github.io/Blazor-ApexCharts/candlestick-charts#mixed

**Comment by joadan** [comment]
Fixed in [v0.9.3-beta](https://github.com/apexcharts/Blazor-ApexCharts/releases/tag/v0.9.2-beta)

**Comment by ShrewdMensch** [comment]
Thanks for you prompt response and fix, Joakim.
I will update the nugget package and try it out

**Comment by ShrewdMensch** [comment]
Hello,
I am still getting the error and I have updated to version 0.9.3-beta.

Below is my .csproj file:

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="0.9.3-beta" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Radzen.Blazor" Version="3.16.6" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IWK">
      <HintPath>..\..\..\..\..\..\Build\V12\IWGIV12_Binaries\IWK.dll</HintPath>
    </Reference>
    <Reference Include="IWNet">
      <HintPath>..\..\..\..\..\..\Build\V12\IWGIV12_Binaries\IWNet.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>

Kindly assist.
THanks

**Comment by joadan** [comment]
Sorry for this, the fix is included in  [v0.9.4-beta](https://github.com/apexcharts/Blazor-ApexCharts/tree/v0.9.4-beta)

**Comment by ShrewdMensch** [comment]
@joadan , I will try it out again.
Thanks

**Comment by ShrewdMensch** [comment]
I am fine now.
Thanks, @joadan
